import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | PersonnaPress",
  description: "PersonnaPress Terms of Service",
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <article className="prose max-w-3xl mx-auto px-6 py-12">
      <p className="not-prose mb-6">
        <Link href="/" className="text-sm text-[#555555] hover:text-[#111111] underline underline-offset-2">
          Back to PersonnaPress
        </Link>
      </p>

      <h1>Terms of Service</h1>
      <p className="lead">Effective date: July 2026</p>

      <h2>1. Service</h2>
      <p>
        PersonnaPress is an AI-powered content generation and multi-platform
        publishing tool that supports publishing to Facebook Pages, Instagram,
        Threads, X (Twitter), LinkedIn, WordPress, WordPress.com, GitHub Pages,
        and Webflow. By using PersonnaPress, you agree to these Terms of
        Service.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 18 years old to use PersonnaPress. The service is
        available for both personal and business use.
      </p>

      <h2>3. Acceptable Use</h2>
      <p>You agree not to use PersonnaPress to:</p>
      <ul>
        <li>Send spam or unsolicited bulk content to any connected platform</li>
        <li>Generate or publish illegal, defamatory, or harmful content</li>
        <li>
          Violate the terms of service of any connected platform, including but
          not limited to Meta (Facebook, Instagram, Threads), X Corp, LinkedIn,
          Automattic (WordPress.com), GitHub, and Webflow
        </li>
        <li>
          Use the service in a way that violates Meta&apos;s Platform Terms or
          Developer Policies, including misrepresenting your identity or the
          purpose of published content
        </li>
        <li>
          Attempt to circumvent any rate limits, access controls, or usage
          quotas within the service or on connected platforms
        </li>
        <li>
          Reverse-engineer, decompile, or attempt to extract the source code of
          PersonnaPress
        </li>
      </ul>

      <h2>4. Subscription and Billing</h2>
      <ul>
        <li>
          All new accounts receive a <strong>14-day free trial</strong> with no
          credit card required.
        </li>
        <li>Billing is handled by Stripe after you upgrade to a paid plan.</li>
        <li>
          If you cancel, you retain access to your plan until the end of the
          current billing period.
        </li>
        <li>
          Subscription fees are non-refundable except where required by
          applicable law.
        </li>
      </ul>

      <h2>5. Content Ownership</h2>
      <p>
        You own all content generated by PersonnaPress. We claim no license
        over your content beyond what is strictly necessary to operate the
        service (storage, CDN delivery, and processing by our AI providers).
        You are responsible for ensuring that any content you publish complies
        with applicable laws and the terms of the platforms you publish to.
      </p>

      <h2>6. AI-Generated Content</h2>
      <p>
        AI-generated content may be inaccurate, incomplete, or not suitable for
        publication without review. You are responsible for reviewing and
        approving all content before publishing it to any platform.
        PersonnaPress is not liable for content published to third-party
        platforms, including any consequences arising from violations of those
        platforms&apos; policies.
      </p>

      <h2>7. Third-Party Platform Connections</h2>
      <p>
        PersonnaPress connects to third-party platforms on your behalf using
        OAuth credentials you authorize. You are responsible for maintaining
        the security of your connected accounts. We are not responsible for any
        actions taken on connected platforms as a result of content you publish
        through PersonnaPress. You can disconnect any platform at any time from
        your client&apos;s Connections page.
      </p>

      <h2>8. Termination</h2>
      <p>
        You may delete your account at any time from the{" "}
        <Link href="/settings">Settings page</Link>. We may suspend or
        terminate accounts that violate these terms, with or without prior
        notice. Upon termination, your data will be deleted in accordance with
        our <Link href="/privacy">Privacy Policy</Link>.
      </p>

      <h2>9. Disclaimer of Warranties</h2>
      <p>
        PersonnaPress is provided &ldquo;as is&rdquo; and &ldquo;as
        available&rdquo; without warranties of any kind, either express or
        implied, including but not limited to warranties of merchantability,
        fitness for a particular purpose, or non-infringement. We do not
        warrant that the service will be uninterrupted, error-free, or free of
        viruses or other harmful components.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by applicable law, PersonnaPress and
        its affiliates, officers, employees, and agents shall not be liable for
        any indirect, incidental, special, consequential, or punitive damages,
        including but not limited to loss of profits, data, or goodwill,
        arising from your use of or inability to use the service. Our total
        liability to you for any claim arising from or related to these terms
        or the service shall not exceed the amount you paid to PersonnaPress in
        the 12 months preceding the claim.
      </p>

      <h2>11. Changes to These Terms</h2>
      <p>
        We will notify you by email or in-app notification before any material
        changes to these terms take effect. Continued use of PersonnaPress
        after changes constitutes acceptance.
      </p>

      <h2>12. Governing Law</h2>
      <p>
        These terms are governed by and construed in accordance with the laws
        of the jurisdiction in which PersonnaPress operates, without regard to
        its conflict of law principles. Any disputes arising under these terms
        shall be resolved in the courts of that jurisdiction.
      </p>

      <h2>Questions</h2>
      <p>
        Contact us at{" "}
        <a href="mailto:support@personnapress.com">support@personnapress.com</a>.
      </p>
    </article>
  );
}
