import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | PersonnaPress",
  description: "PersonnaPress Terms of Service",
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <article className="prose max-w-3xl mx-auto px-6 py-12">
      <p className="not-prose mb-6">
        <Link href="/" className="text-sm text-[#555555] hover:text-[#111111] underline underline-offset-2">
          Back to PersonnaPress
        </Link>
      </p>

      <h1>Terms of Service</h1>
      <p className="lead">Effective date: July 2026</p>

      <h2>1. Service</h2>
      <p>
        PersonnaPress is an AI-powered content generation and multi-platform
        publishing tool. By using PersonnaPress, you agree to these Terms of Service.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 18 years old to use PersonnaPress. The service is
        available for both personal and business use.
      </p>

      <h2>3. Acceptable Use</h2>
      <p>You agree not to use PersonnaPress to:</p>
      <ul>
        <li>Send spam or unsolicited bulk content to connected platforms</li>
        <li>Generate or publish illegal content</li>
        <li>Violate the terms of service of any connected platform (WordPress, X, LinkedIn, etc.)</li>
        <li>Attempt to circumvent any limits or access controls within the service</li>
      </ul>

      <h2>4. Subscription and Billing</h2>
      <ul>
        <li>
          All new accounts receive a <strong>14-day free trial</strong> with no
          credit card required.
        </li>
        <li>
          Billing is handled by Stripe after you upgrade to a paid plan.
        </li>
        <li>
          If you cancel, you retain access to your plan until the end of the current
          billing period.
        </li>
      </ul>

      <h2>5. Content Ownership</h2>
      <p>
        You own all content generated by PersonnaPress. We claim no license over
        your content beyond what is strictly necessary to operate the service
        (storage, CDN delivery, and processing by our AI providers).
      </p>

      <h2>6. Limitations</h2>
      <p>
        AI-generated content may be inaccurate, incomplete, or not suitable for
        publication without review. You are responsible for reviewing and approving
        all content before publishing it to any platform. PersonnaPress is not
        liable for content published to third-party platforms.
      </p>

      <h2>7. Termination</h2>
      <p>
        You may delete your account at any time from the{" "}
        <Link href="/account">Account page</Link>. We may suspend or terminate
        accounts that violate these terms.
      </p>

      <h2>8. Changes to These Terms</h2>
      <p>
        We will notify you by email or in-app notification before any material
        changes to these terms take effect. Continued use of PersonnaPress after
        changes constitutes acceptance.
      </p>

      <h2>Questions</h2>
      <p>
        Contact us at{" "}
        <a href="mailto:support@personnapress.com">support@personnapress.com</a>.
      </p>
    </article>
  );
}
