"""Multi-platform publish worker.

Receives job_id and campaign_id from the router's BackgroundTask and runs
dispatch_publish. Creates its own DB session (the request-scoped session is
closed before BackgroundTasks execute).
"""

import json
import logging
from uuid import UUID

from app.core.exceptions import PlatformError
from app.core.security import decrypt_credential, encrypt_credential
from app.db.connection import get_session_context
from app.db.repositories.campaigns import get_campaign, update_campaign_scheduled_at, update_campaign_status
from app.db.repositories.jobs import update_job
from app.db.repositories.models import utcnow
from app.db.repositories.platform_connections import get_connections_for_client, upsert_connection
from app.integrations import github as github_integration
from app.services.articles import create_or_update_article_from_campaign
from app.services.publishing import dispatch_publish, generate_github_post_file, _refresh_token_if_needed
from app.db.repositories.articles import get_article_by_campaign_id

logger = logging.getLogger(__name__)


async def publish_github_job(
    job_id: UUID,
    campaign_id: UUID,
    mode: str,
    author: str | None = None,
    categories: list[str] | None = None,
) -> None:
    """BackgroundTask entry point for GitHub PR or direct-commit publishing."""
    async with get_session_context() as db:
        await update_job(db, job_id, status="in_progress", started_at=utcnow())
        await db.commit()
        try:
            campaign = await get_campaign(db, campaign_id)
            if not campaign:
                raise RuntimeError(f"Campaign {campaign_id} not found")

            connections = await get_connections_for_client(db, campaign.client_id)
            github_conn = next((c for c in connections if c.platform == "github_pages"), None)
            if not github_conn:
                raise PlatformError("github", 0, "GitHub connection not found")

            cred = json.loads(decrypt_credential(github_conn.encrypted_credentials))
            cred = await _refresh_token_if_needed(cred, db, campaign.client_id)
            installation_token: str = cred["installation_token"]
            repo_full_name: str = cred.get("repo_full_name", "")
            if not repo_full_name:
                raise PlatformError("github", 0, "No repository selected")

            file_path, file_content, commit_message, title = await generate_github_post_file(campaign, cred, db, author=author, categories=categories)
            if file_path is None:
                raise PlatformError("github", 0, "Content folder not detected; set publish path in connections first")

            if mode == "pr":
                default_branch = await github_integration.get_default_branch(installation_token, repo_full_name)
                branch_sha = await github_integration.get_branch_sha(installation_token, repo_full_name, default_branch)
                branch_name = f"personnapress/{str(campaign_id)[:8]}"
                await github_integration.create_branch(installation_token, repo_full_name, branch_name, branch_sha)
                await github_integration.create_file_commit(
                    installation_token, repo_full_name, file_path, file_content, commit_message, branch=branch_name
                )
                pr_title = title[:72]
                pr_body = f"**Target file:** `{file_path}`\n\nGenerated by PersonnaPress"
                pr_url = await github_integration.create_pull_request(
                    installation_token, repo_full_name, branch_name, default_branch, pr_title, pr_body
                )
                campaign.github_pr_url = pr_url
                db.add(campaign)
                await db.commit()
                await update_job(
                    db, job_id, status="complete",
                    error_details=json.dumps({"pr_url": pr_url, "title": title}),
                    completed_at=utcnow(),
                )
                await db.commit()
            else:
                commit_sha = await github_integration.create_file_commit(
                    installation_token, repo_full_name, file_path, file_content, commit_message
                )
                campaign.github_pr_url = None
                db.add(campaign)
                await update_campaign_status(db, campaign_id, "published")
                await update_job(
                    db, job_id, status="complete",
                    error_details=json.dumps({"commit_sha": commit_sha, "repo_full_name": repo_full_name}),
                    completed_at=utcnow(),
                )
                await db.commit()
                campaign = await get_campaign(db, campaign_id)
                if campaign is not None:
                    try:
                        await create_or_update_article_from_campaign(db, campaign)
                        await db.commit()
                    except Exception:
                        logger.error("Article creation failed for campaign=%s", campaign_id, exc_info=True)

        except Exception as exc:
            logger.error("GitHub publish error job=%s: %s", job_id, exc, exc_info=True)
            error_msg = exc.message if isinstance(exc, PlatformError) else str(exc)[:200]
            await update_job(
                db, job_id, status="failed",
                error_details=json.dumps({"platform": "github_pages", "message": error_msg}),
                completed_at=utcnow(),
            )
            await db.commit()


async def run_publish(job_id: UUID, campaign_id: UUID, platforms: list[str] | None = None) -> None:
    """BackgroundTask entry point for multi-platform publishing."""
    if platforms is None:
        platforms = []
    async with get_session_context() as db:
        await update_job(db, job_id, status="in_progress", started_at=utcnow())
        await db.commit()
        try:
            results = await dispatch_publish(db, campaign_id, job_id, platforms)
            all_success = all(v in ("success", "already_published") for v in results.values()) and bool(results)
            if all_success:
                await update_campaign_status(db, campaign_id, "published")
                await update_campaign_scheduled_at(db, campaign_id, None)
                await update_job(db, job_id, status="complete", error_details=json.dumps(results), completed_at=utcnow())
                await db.commit()
                campaign = await get_campaign(db, campaign_id)
                if campaign is not None:
                    try:
                        await create_or_update_article_from_campaign(db, campaign)
                        await db.commit()
                    except Exception:
                        logger.error("Article creation failed for campaign=%s", campaign_id, exc_info=True)
            else:
                await update_campaign_status(db, campaign_id, "failed")
                await update_campaign_scheduled_at(db, campaign_id, None)
                await update_job(
                    db,
                    job_id,
                    status="failed",
                    error_details=json.dumps(results),
                    completed_at=utcnow(),
                )
            await db.commit()
        except Exception as exc:
            logger.error("Fatal publish error job=%s: %s", job_id, exc, exc_info=True)
            await update_campaign_status(db, campaign_id, "failed")
            await update_campaign_scheduled_at(db, campaign_id, None)
            await update_job(
                db,
                job_id,
                status="failed",
                error_details=json.dumps({"error": str(exc)}),
                completed_at=utcnow(),
            )
            await db.commit()


async def run_publish_headless(campaign_id_str: str) -> None:
    """APScheduler fires this to flip a scheduled headless article from hidden to published."""
    from uuid import UUID as _UUID
    try:
        campaign_id = _UUID(campaign_id_str)
    except (ValueError, AttributeError):
        logger.error("run_publish_headless: invalid campaign_id=%r — skipping", campaign_id_str)
        return
    async with get_session_context() as db:
        article = await get_article_by_campaign_id(db, campaign_id)
        if not article:
            logger.warning("run_publish_headless: no article for campaign=%s — skipping", campaign_id)
            return
        if str(getattr(article.status, "value", article.status)) == "published":
            logger.info("run_publish_headless: article=%s already published — skipping", article.id)
            return
        article.status = "published"
        article.updated_at = utcnow()
        db.add(article)
        await db.commit()
        logger.info("run_publish_headless: article=%s published (campaign=%s)", article.id, campaign_id)
