"""add_voice_samples_to_clients

Revision ID: 5c08a8909153
Revises: 4789135e4739
Create Date: 2026-09-08 17:19:10.910651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c08a8909153'
down_revision: Union[str, Sequence[str], None] = '4789135e4739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('clients', sa.Column('voice_samples', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_post_metrics_client_id'), table_name='post_metrics')
    op.drop_index(op.f('ix_post_metrics_post_captured'), table_name='post_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_metrics_post_captured'), 'post_metrics', ['published_post_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_index(op.f('ix_post_metrics_client_id'), 'post_metrics', ['client_id'], unique=False)
    op.drop_column('clients', 'voice_samples')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
