"""add_article_template_to_campaigns

Revision ID: ae296c4a3414
Revises: 4317d2f4b9b7
Create Date: 2026-08-10 18:11:35.650920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae296c4a3414'
down_revision: Union[str, Sequence[str], None] = '4317d2f4b9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('article_template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'article_template')
    # ### end Alembic commands ###
